import { collection, addDoc, onSnapshot, doc } from 'firebase/firestore';
import { db } from './firebase';

// Stripe Publishable Key from environment variables
// Falls back to test key for local development if not set
const STRIPE_PUBLISHABLE_KEY = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY || "pk_test_51StBKbDXnXONl2svilQpGduggNMqelrS6j6EEiOfTTjHgyLPI1k0KM1nVntIvxW1hHHNti5TycjCk4bc6T4n3B9g00wrV26qnX";

// Price IDs from environment variables
// Falls back to test price for local development if not set
export const PRICE_IDS = {
    STARTER_10PLN: import.meta.env.VITE_STRIPE_PRICE_STARTER || "price_1StBSvDXnXONl2svkF51zTnl",
    PRO_50PLN: import.meta.env.VITE_STRIPE_PRICE_PRO || "price_1Sw7KFDXnXONl2svPmtUXAxk"
};

export const getStripe = async () => {
    // If using the <script> tag in index.html, Stripe is available on window
    const Stripe = (window as any).Stripe;
    if (!Stripe) {
        throw new Error("Stripe.js has not loaded yet.");
    }
    return Stripe(STRIPE_PUBLISHABLE_KEY);
};

/**
 * Creates a Stripe Checkout Session for the current user.
 * The Stripe extension will detect the new document in Firestore,
 * create a session on Stripe's side, and update the document with a 'url'.
 */
export const createCheckoutSession = async (uid: string, priceId: string) => {
    try {
        const checkoutSessionsRef = collection(db, 'customers', uid, 'checkout_sessions');

        // 1. Create a session document in Firestore
        const docRef = await addDoc(checkoutSessionsRef, {
            price: priceId,
            success_url: window.location.origin,
            cancel_url: window.location.origin,
            mode: 'subscription', // or 'payment' for one-time
            collect_shipping_address: false,
        });

        // 2. Listen for the URL to be added by the Stripe Extension
        return new Promise<string>((resolve, reject) => {
            const unsubscribe = onSnapshot(docRef, (snap) => {
                const { url, error } = snap.data() as any;
                if (url) {
                    unsubscribe();
                    resolve(url);
                }
                if (error) {
                    unsubscribe();
                    reject(new Error(`Stripe error: ${error.message}`));
                }
            });
        });
    } catch (error) {
        console.error("Error creating checkout session:", error);
        throw error;
    }
};

/**
 * Helper to open the Stripe Customer Portal
 * (Requires the extension to have created a portal link)
 */
export const openCustomerPortal = async () => {
    // This is typically handled by another Cloud Function or looking up a URL
    // generated by the extension in Firestore.
    window.open('https://billing.stripe.com/p/portal/YOUR_PORTAL_LINK', '_blank');
};
